"""enumerate Role.name in backend

Revision ID: 6528f449b71a
Revises: b48d2ccc2049
Create Date: 2026-04-12 01:47:24.508862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6528f449b71a'
down_revision: Union[str, Sequence[str], None] = 'b48d2ccc2049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Role', type_='unique')
    # ### end Alembic commands ###
