"""initial migration

Revision ID: f217c6678dc9
Revises:
Create Date: 2026-04-06 21:55:20.803368

"""

import random
from datetime import datetime, timedelta
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f217c6678dc9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quota", sa.SmallInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Event_id"), "Event", ["id"], unique=False)
    op.create_table(
        "Role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Role_id"), "Role", ["id"], unique=False)
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("whatsapp", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_User_id"), "User", ["id"], unique=False)
    op.create_table(
        "Account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=16), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["Role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_Account_id"), "Account", ["id"], unique=False)
    op.create_table(
        "Registration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["Event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["User.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Registration_id"), "Registration", ["id"], unique=False)
    op.create_table(
        "Log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=75), nullable=False),
        sa.Column("ip_address", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.Column("entity", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["Account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Log_id"), "Log", ["id"], unique=False)
    # ### end Alembic commands ###
    #
    #
    role_table = sa.table("Role", sa.column("id"), sa.column("name"))
    roles = [
        {"id": i, "name": name}
        for i, name in enumerate(
            [
                "Admin",
                "Staff",
                "User",
                "Guest",
                "Moderator",
                "Editor",
                "Manager",
                "Analyst",
                "Support",
                "Tester",
            ],
            1,
        )
    ]
    op.bulk_insert(role_table, roles)

    event_table = sa.table(
        "Event",
        sa.column("id"),
        sa.column("name"),
        sa.column("description"),
        sa.column("quota"),
    )
    events = []
    for i in range(1, 11):
        events.append(
            {
                "id": i,
                "name": f"Tech Conference 2026 Vol {i}",
                "description": f"Description for event {i}",
                "quota": random.randint(50, 200),
            }
        )
    op.bulk_insert(event_table, events)

    user_table = sa.table(
        "User",
        sa.column("id"),
        sa.column("first_name"),
        sa.column("last_name"),
        sa.column("whatsapp"),
    )
    users = []
    for i in range(1, 11):
        users.append(
            {
                "id": i,
                "first_name": f"UserFN_{i}",
                "last_name": f"UserLN_{i}",
                "whatsapp": f"62812345678{i}",
            }
        )
    op.bulk_insert(user_table, users)

    account_table = sa.table(
        "Account",
        sa.column("id"),
        sa.column("user_id"),
        sa.column("role_id"),
        sa.column("email"),
        sa.column("username"),
        sa.column("password"),
    )
    accounts = []
    for i in range(1, 11):
        accounts.append(
            {
                "id": i,
                "user_id": i,  # 1-to-1 mapping for simplicity
                "role_id": i,  # Linked to roles 1-10
                "email": f"user{i}@example.com",
                "username": f"user_{i}",
                "password": "hashed_password_placeholder",
            }
        )
    op.bulk_insert(account_table, accounts)

    reg_table = sa.table(
        "Registration", sa.column("id"), sa.column("user_id"), sa.column("event_id")
    )
    registrations = []
    for i in range(1, 11):
        registrations.append({"id": i, "user_id": i, "event_id": random.randint(1, 10)})
    op.bulk_insert(reg_table, registrations)

    log_table = sa.table(
        "Log",
        sa.column("id"),
        sa.column("account_id"),
        sa.column("action"),
        sa.column("ip_address"),
        sa.column("user_agent"),
        sa.column("entity"),
    )
    logs = []
    actions = ["LOGIN", "UPDATE_PROFILE", "CREATE_BLOG", "LOGOUT", "DELETE_POST"]
    entities = ["Account", "Blog", "Event", "Registration"]
    for i in range(1, 11):
        logs.append(
            {
                "id": i,
                "account_id": i,
                "action": random.choice(actions),
                "ip_address": f"192.168.1.{10 + i}",
                "user_agent": "Mozilla/5.0 (X11; Linux x86_64)",
                "entity": random.choice(entities),
            }
        )
    op.bulk_insert(log_table, logs)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Log_id"), table_name="Log")
    op.drop_table("Log")
    op.drop_index(op.f("ix_Registration_id"), table_name="Registration")
    op.drop_table("Registration")
    op.drop_index(op.f("ix_Account_id"), table_name="Account")
    op.drop_table("Account")
    op.drop_index(op.f("ix_User_id"), table_name="User")
    op.drop_table("User")
    op.drop_index(op.f("ix_Role_id"), table_name="Role")
    op.drop_table("Role")
    op.drop_index(op.f("ix_Event_id"), table_name="Event")
    op.drop_table("Event")
    # ### end Alembic commands ###
