"""Role seeding

Revision ID: fc70450c9eb3
Revises: 6528f449b71a
Create Date: 2026-04-21 04:06:51.897763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fc70450c9eb3"
down_revision: Union[str, Sequence[str], None] = "6528f449b71a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO \"Role\" (name) VALUES ('SuperAdmin')")
    op.execute("INSERT INTO \"Role\" (name) VALUES ('Admin')")
    op.execute("INSERT INTO \"Role\" (name) VALUES ('User')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM "Role"')
    # ### end Alembic commands ###
